<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Portfolio_about</title>
	<meta charset="utf-8">
	<link rel='stylesheet' href='main.css'>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet">
	
</head>
<body>
	<?php include 'header1.phtml'; ?>
	<main id='princAbout'>
		<section>
			<div id='fond'>
		
			</div>
		</section>
			
		<section id='corps'>
			<div id='second'>
				<div id='cv'>
					<img src='images/sainte-victoire.jpg'/>
				</div>
			</div>
				
			<div id='premier'>
				<p>Installé à Aix-en-Provence, je suis actuellement étudiant
				en Développement Web et Web mobile au Greta Provence.</p>
						 
				<p > Passionné depuis longtemps de technologie Web, je réalise des sites depuis 2018.</p>
				
				<p >Amoureux de la nature, je me promène souvent dans le massif de la Sainte-Victoire avec mes deux enfants.</p>
			</div>
			
			
			<div id='troisieme'>
				<a href='images/CV.pdf' target="_blank"><img src='images/logo1.png'/></a>
			</div>
			
											
		</section>
		
		<footer>
		</footer>
	</main>
	<script src='js/main.js'></script>
</body>
</html>