<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Portfolio_contact</title>
	<meta charset="utf-8">
	<link rel='stylesheet' href='main.css'>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet">

<body>
	<?php include 'header1.phtml'; ?>
	<main id='princContact'>
		<section id='corps'>
			<div id='fond'>
			
			</div>
		</section>
			
		<section id='corps1'>
			
			<p><em>Une envie ? Un besoin ?</br>
			Contactez-moi !</em></p>
				
			<p>Daniel Provost</br>
			dprovost67@gmail.com</br>
			0689118020</p>
				
		<div id='logoL'>
				
				
			
		
			<a href='https://www.linkedin.com/in/daniel-provost67' target="_blank"><img src='images/linkedin1.png' alt=''/></a>
				
		</div>
		</section>
		
		<footer>
		
		</footer>
	</main>
	<script src='js/main.js'></script>
</body>
</html>