<header>
	<div id='menu'>
	
		<div id='burger'>
		<div class='burger'></div>
		<div class='burger'></div>
		<div class='burger'></div>
		</div>
		
		<nav>
			<ul id='repartition'>
				<li>
					<dl>
						<dt><a href='index.php' title='' id='index'>Home</a></dt>
						
					</dl>
				</li>
				
				<li>
					<dl>
						<dt><a href='about.php' title='' id='about'>About</a></dt>
						
					</dl>
				</li>
				<li>
					<dl>
						<dt><a href='#' title='' id='work'>Work</a></dt>
						
						<dd>
							<ul>
								<li><a href='work1.php' title='' id='work1'>2018</a></li>                     
								<li><a href='work2.php' title='' id='work2'>2019</a></li>  
								
							</ul>
						</dd>
					</dl>
				</li>
				<li>
					<dl>
						<dt><a href='contact.php' title='' id='contact'>Contact</a></dt>
						
						
					</dl>
				</li>
			</ul>	
		</nav>
	</div>	
</header>