<header>
		<i class="fas fa-bars" id='menu'></i>
		<nav>
		
			
			<ul id='repartition'>
				<li>
					<dl>
						<dt><a href='index.php' title=''><em>Home</em></a></dt>
						
					</dl>
				</li>
				
				<li>
					<dl>
						<dt><a href='about.php' title='' id='about'><em>About</em></a></dt>
						
					</dl>
				</li>
				<li>
					<dl>
						<dt><a href='#' title='' id='work'><em>Work</em></a></dt>
						
						<dd>
							<ul>
								<li><a href='work1.php' title='' id='work1'><em>2018</em></a></li>                     
								<li><a href='work2.php' title='' id='work2'><em>2019</em></a></li>  
								
							</ul>
						</dd>
					</dl>
				</li>
				<li>
					<dl>
						<dt><a href='contact.php' title='' id='contact'><em>Contact</em></a></dt>
						
						
					</dl>
				</li>
			</ul>	
		</nav>
		
</header>