<!DOCTYPE html>
<html lang="fr">
	<head>
	<title>Portfolio_home</title>
	<meta charset="utf-8">
	<link rel='stylesheet' href='main.css'>
	<link href="https://fonts.googleapis.com/css?family=Lato:300i" rel="stylesheet"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	</head>
	<body>
	<?php include 'header1.phtml'; ?>
		<main id="principal">
			<section>
				<div id='fond'>			
				</div>
			</section>
				
		<section>		
			<div id='titre'>
				<h1><em>Portfolio</em></br>Web developement</h1>			
			</div>	
			
			<div id='basdepage'>
				<p><em><a href='contact.php' title=''>Daniel Provost - Web developer</a></em></p>
			</div>
			
		</section>
		</main>
		<script src='js/main.js'></script>
	</body>
</html>
	