<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Portfolio_contact</title>
	<meta charset="utf-8">
	<link rel='stylesheet' href='main.css'>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet">
	
</head>
<body>
	<?php include 'header1.phtml'; ?>
	<main id='princWork1'>
		<section >
			<div id='webAgency'>
			<a href='https://dprovost67.000webhostapp.com/' target="_blank"><img src='images/webAgency1.png'/></a>
			</div>	
		
		<div id='texteWeb'>
				<p>Travail réalisé en mai 2018 d'après une maquette d'une agence Web</br><a href='https://dprovost67.000webhostapp.com/' target="_blank">- cliquez sur l'image -</p></a>
			</div>	
			
		</section>
		
		<section>
			<div id='fond_work1'>
				
			</div>
			
		</section>
			
		<section>
			<div id='texteStr'>
				<p>Site Wordpress réalisé en juillet 2018</br>
				<a href='http://office.themecloud.website/' target="_blank">- cliquez sur l'image -</p></a>
			</div>
			<div id='siteStr'>
				<a href='http://office.themecloud.website/' target="_blank"><img src='images/siteStrasbourg.png' alt=''/></a>
			</div>
		</section>
					
		<footer>	
		</footer>
	</main>
	<script src='js/main.js'></script>
</body>
</html>