<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Portfolio_contact</title>
	<meta charset="utf-8">
	<link rel='stylesheet' href='main.css'>
	<link href="https://fonts.googleapis.com/css?family=Lato:300" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
</head>
<body>
	<?php include 'header1.phtml'; ?>
	<main>
		
		<section>
			<div id='fond1'>
				
				<div id='image'>
					<img src='images/hanami1.png' alt=''/>
				</div>
				
				<div id='texte'>
					<p> Site réalisé sur commande (non encore mise en ligne).</br> A propos des fêtes accompagnant le retour du printemps avec un calendrier prévisionnel.</p>
				</div>
				
			</div>

			
			
			<div id='fond2'>
			
				
			
			</div>
			
			
			
			<div id='fond3'>
			
				<div id='texte1'>
				</div>
				
				<div id='image1'>
					 <img src='images/hanami2.png' alt=''/>
				</div>
			
			
			</div>
			
			
		</section>
	</main>
	<script src='js/main.js'></script>
</body>
</html>